title: canapé
tagline: en début de la soirée
host: http://fikovnik.net

pygments: true
markdown: kramdown
permalink: pretty

exclude:

- fabfile.py
- fabfile.pyc
- gen-gallery.py
- gen-gallery.pyc
- CNAME

sections:

- name: about
  title: about

- name: research
  title: research

#- name: journal
#  title: journal

galleries:

- name: book1
  title: book one 

- name: book2
  title: book two

- name: book3
  title: book three

projects:

- name: the-rickshaw-run-2009
  title: the rickshaw run 2009
