title: canapé
host: http://fikovnik.net

pygments: true
markdown: kramdown
permalink: pretty

exclude:

- canape.sh
- gen-gallery.py 

sections:

- name: about
  title: about

- name: research
  title: research

- name: journal
  title: journal

projects:

- name: the-rickshaw-run-2009
  title: the rickshaw run 2009
