title: Filip Křikava

author: Filip Krikava

twitter: fikovnik

permalink: pretty

exclude:
- sass
- config.rb
- Gemfile
- CNAME

sections:
- name: root
  title: "" 
- name: projects
  title: projects


prose:
  rooturl: "_posts"
  siteurl: "http://fikovnik.net/"
  media: "media"
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "journal"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _posts/exhibit:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "category"
        field:
          element: "hidden"
          value: "journal"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "section"
        field:
          element: "select"
          label: "Sections"
          options:
            - name: "Projects"
              value: "projects"
            - name: "Root"
              value: "root"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""