title: fikovnik.net

host: http://fikovnik.net

author: Filip Krikava

twitter: fikovnik

permalink: none

exclude:

- sass
- config.rb
- Gemfile
- fabfile.py
- fabfile.pyc
- gen-gallery.py
- gen-gallery.pyc
- CNAME


prose:
  rooturl: "_posts/"
  metadata: 
    "_posts/exhibits": |
      layout: default
      category: exhibit
      title: "El titulo del exhibit"
      section: "La sección a la que pertenece este exhibit"
    "_posts/sections": |
      layout: default
      category: section
      title: "El título de la sección"